#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_API_GATEWAY_PORT text "Port" 8080

  if [ ! -f "$SERVICE_API_GATEWAY_CONFIG" ]; then
    log::error "config file not found: $SERVICE_API_GATEWAY_CONFIG"
    exit 1
  fi
}

check $@
